const { defineConfig } = require('eslint/config');
const eslintJs = require('@eslint/js');
const eslintImport = require('eslint-plugin-import');
const babelParser = require('@babel/eslint-parser');
const globals = require('globals');

module.exports = defineConfig([
  {
    extends: [
      eslintJs.configs.recommended,
      eslintImport.flatConfigs.recommended,
    ],
    linterOptions: {
      reportUnusedInlineConfigs: 'warn',
      reportUnusedDisableDirectives: 'warn',
    },
    languageOptions: {
      sourceType: 'commonjs',
      parser: babelParser,
      globals: { ...globals.node, ...globals.jest },
    },
    rules: {
      'array-callback-return': ['error', { allowImplicit: true }],
      'block-scoped-var': 'error',
      'class-methods-use-this': 'error',
      'default-case': 'error',
      'default-case-last': 'error',
      'default-param-last': 'error',
      'dot-notation': 'error',
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'grouped-accessor-pairs': 'error',
      'guard-for-in': 'error',
      'max-classes-per-file': ['error', 1],
      'no-caller': 'error',
      'no-constructor-return': 'error',
      'no-else-return': 'error',
      'no-empty-function': ['error', { allow: ['arrowFunctions'] }],
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-floating-decimal': 'error',
      'no-implicit-coercion': 'error',
      'no-implied-eval': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-proto': 'error',
      'no-return-assign': ['error', 'always'],
      'no-return-await': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unused-expressions': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'prefer-promise-reject-errors': ['error', { allowEmptyReject: true }],
      'prefer-regex-literals': 'error',
      yoda: 'error',
      'no-async-promise-executor': 'error',
      'no-await-in-loop': 'error',
      'no-inner-declarations': 'error',
      'no-promise-executor-return': 'error',
      'no-unreachable-loop': 'error',
      'valid-typeof': ['error', { requireStringLiterals: true }],
      'arrow-body-style': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-var': 'error',
      'prefer-const': [
        'error',
        {
          ignoreReadBeforeAssign: true,
        },
      ],
      'prefer-numeric-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'require-yield': 'error',
      'no-bitwise': 'error',
      'no-lonely-if': 'error',
      'no-multi-assign': 'error',
      'no-nested-ternary': 'error',
      'no-underscore-dangle': [
        'error',
        {
          enforceInMethodNames: true,
        },
      ],
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'prefer-object-spread': 'error',
      'no-delete-var': 'error',
      'no-shadow-restricted-names': 'error',
      'no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_+', varsIgnorePattern: '^_+' },
      ],
      'no-use-before-define': 'error',
      'import/first': 'error',
      'import/newline-after-import': [
        'error',
        { exactCount: true, considerComments: true },
      ],
      'import/no-absolute-path': 'error',
      'import/no-cycle': 'error',
      'import/no-self-import': 'error',
    },
  },
]);
