version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    docker:
      - image: cimg/node:16.4
    steps:
      - checkout
      - run: node --version
          
  tests-and-linters:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm test
      - run: npm run eslint

workflows:
  build:
    jobs:
      - build
      - tests-and-linters
