name: Feature Request
description: Suggest a new feature or an enhancement to an existing feature
labels: ["Status: Needs Review"]
assignees:
  - nil
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a new feature request to The Odin Project. In order to get issues closed in a reasonable amount of time, you must include a baseline of information about the feature/enhancement you are proposing. Please read this template in its entirety before filling it out to ensure that it is filled out correctly
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Please fill out the following checkboxes
      options:
        - label: I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
          required: true
        - label: "The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter``"
          required: true
  - type: checkboxes
    id: assigned
    attributes:
      label: Do you want to be assigned to this issue?
      description: Completing this checkbox does not guarantee you will be assigned this issue, but rather lets us know you are interested in working on it
      options:
        - label: I would like to be assigned this issue to work on it
          required: false
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the Feature Request
      description: |
        A clear and concise description of what the feature or enhancement is, including how it would be useful/beneficial or what problem(s) it would solve.

        When suggesting an entirely new command, it can be helpful to include what text you believe should trigger the command, e.g. `/commandName` or `/commandName @user`.
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: A list of checkbox items that explain the requirements needed to be met to resolve this request.
      placeholder: |
        - [ ] A theme toggle is present on the dashboard
        - [ ] Clicking the theme toggle changes between light and dark
        - [ ] A user's theme choice persists after leaving the website
      render: "[tasklist]"
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Any additional information about the feature request, such as a link to a Discord discussion, screenshots, etc.
